/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class pers_zhc_test_jni_JNI */

#ifndef _Included_pers_zhc_test_jni_JNI
#define _Included_pers_zhc_test_jni_JNI
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     pers_zhc_test_jni_JNI
 * Method:    speak
 * Signature: (Ljava/lang/String;)V
 */
JNIEXPORT void JNICALL Java_pers_zhc_test_jni_JNI_speak
  (JNIEnv *, jclass, jstring);

#ifdef __cplusplus
}
#endif
#endif
