# CMAKE generated file: DO NOT EDIT!
# Generated by "Unix Makefiles" Generator, CMake Version 3.10

# Default target executed when no arguments are given to make.
default_target: all

.PHONY : default_target

# Allow only one "make -f Makefile2" at a time, but pass parallelism.
.NOTPARALLEL:


#=============================================================================
# Special targets provided by cmake.

# Disable implicit rules so canonical targets will work.
.SUFFIXES:


# Remove some rules from gmake that .SUFFIXES does not remove.
SUFFIXES =

.SUFFIXES: .hpux_make_needs_suffix_list


# Suppress display of executed commands.
$(VERBOSE).SILENT:


# A target that is always out of date.
cmake_force:

.PHONY : cmake_force

#=============================================================================
# Set environment variables for the build.

# The shell in which to execute make rules.
SHELL = /bin/sh

# The CMake executable.
CMAKE_COMMAND = /usr/bin/cmake

# The command to remove a file.
RM = /usr/bin/cmake -E remove -f

# Escaping for special characters.
EQUALS = =

# The top-level source directory on which CMake was run.
CMAKE_SOURCE_DIR = /root/cpp

# The top-level build directory on which CMake was run.
CMAKE_BINARY_DIR = /root/cpp

#=============================================================================
# Targets provided globally by CMake.

# Special rule for the target rebuild_cache
rebuild_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Running CMake to regenerate build system..."
	/usr/bin/cmake -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : rebuild_cache

# Special rule for the target rebuild_cache
rebuild_cache/fast: rebuild_cache

.PHONY : rebuild_cache/fast

# Special rule for the target edit_cache
edit_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "No interactive CMake dialog available..."
	/usr/bin/cmake -E echo No\ interactive\ CMake\ dialog\ available.
.PHONY : edit_cache

# Special rule for the target edit_cache
edit_cache/fast: edit_cache

.PHONY : edit_cache/fast

# The main all target
all: cmake_check_build_system
	$(CMAKE_COMMAND) -E cmake_progress_start /root/cpp/CMakeFiles /root/cpp/CMakeFiles/progress.marks
	$(MAKE) -f CMakeFiles/Makefile2 all
	$(CMAKE_COMMAND) -E cmake_progress_start /root/cpp/CMakeFiles 0
.PHONY : all

# The main clean target
clean:
	$(MAKE) -f CMakeFiles/Makefile2 clean
.PHONY : clean

# The main clean target
clean/fast: clean

.PHONY : clean/fast

# Prepare targets for installation.
preinstall: all
	$(MAKE) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall

# Prepare targets for installation.
preinstall/fast:
	$(MAKE) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall/fast

# clear depends
depend:
	$(CMAKE_COMMAND) -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 1
.PHONY : depend

#=============================================================================
# Target rules for targets named diaryCharacterStatistics

# Build rule for target.
diaryCharacterStatistics: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 diaryCharacterStatistics
.PHONY : diaryCharacterStatistics

# fast build rule for target.
diaryCharacterStatistics/fast:
	$(MAKE) -f CMakeFiles/diaryCharacterStatistics.dir/build.make CMakeFiles/diaryCharacterStatistics.dir/build
.PHONY : diaryCharacterStatistics/fast

#=============================================================================
# Target rules for targets named test

# Build rule for target.
test: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 test
.PHONY : test

# fast build rule for target.
test/fast:
	$(MAKE) -f CMakeFiles/test.dir/build.make CMakeFiles/test.dir/build
.PHONY : test/fast

#=============================================================================
# Target rules for targets named T1

# Build rule for target.
T1: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 T1
.PHONY : T1

# fast build rule for target.
T1/fast:
	$(MAKE) -f CMakeFiles/T1.dir/build.make CMakeFiles/T1.dir/build
.PHONY : T1/fast

#=============================================================================
# Target rules for targets named a

# Build rule for target.
a : cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 a
.PHONY : a

# fast build rule for target.
a/fast:
	$(MAKE) -f CMakeFiles/a.dir/build.make CMakeFiles/a.dir/build
.PHONY : a/fast

#=============================================================================
# Target rules for targets named T2

# Build rule for target.
T2: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 T2
.PHONY : T2

# fast build rule for target.
T2/fast:
	$(MAKE) -f CMakeFiles/T2.dir/build.make CMakeFiles/T2.dir/build
.PHONY : T2/fast

#=============================================================================
# Target rules for targets named T3

# Build rule for target.
T3: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 T3
.PHONY : T3

# fast build rule for target.
T3/fast:
	$(MAKE) -f CMakeFiles/T3.dir/build.make CMakeFiles/T3.dir/build
.PHONY : T3/fast

#=============================================================================
# Target rules for targets named fourierSeries

# Build rule for target.
fourierSeries: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 fourierSeries
.PHONY : fourierSeries

# fast build rule for target.
fourierSeries/fast:
	$(MAKE) -f CMakeFiles/fourierSeries.dir/build.make CMakeFiles/fourierSeries.dir/build
.PHONY : fourierSeries/fast

#=============================================================================
# Target rules for targets named T4

# Build rule for target.
T4: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 T4
.PHONY : T4

# fast build rule for target.
T4/fast:
	$(MAKE) -f CMakeFiles/T4.dir/build.make CMakeFiles/T4.dir/build
.PHONY : T4/fast

ComplexIntegral.o: ComplexIntegral.cpp.o

.PHONY : ComplexIntegral.o

# target to build an object file
ComplexIntegral.cpp.o:
	$(MAKE) -f CMakeFiles/T2.dir/build.make CMakeFiles/T2.dir/ComplexIntegral.cpp.o
	$(MAKE) -f CMakeFiles/T3.dir/build.make CMakeFiles/T3.dir/ComplexIntegral.cpp.o
	$(MAKE) -f CMakeFiles/fourierSeries.dir/build.make CMakeFiles/fourierSeries.dir/ComplexIntegral.cpp.o
.PHONY : ComplexIntegral.cpp.o

ComplexIntegral.i: ComplexIntegral.cpp.i

.PHONY : ComplexIntegral.i

# target to preprocess a source file
ComplexIntegral.cpp.i:
	$(MAKE) -f CMakeFiles/T2.dir/build.make CMakeFiles/T2.dir/ComplexIntegral.cpp.i
	$(MAKE) -f CMakeFiles/T3.dir/build.make CMakeFiles/T3.dir/ComplexIntegral.cpp.i
	$(MAKE) -f CMakeFiles/fourierSeries.dir/build.make CMakeFiles/fourierSeries.dir/ComplexIntegral.cpp.i
.PHONY : ComplexIntegral.cpp.i

ComplexIntegral.s: ComplexIntegral.cpp.s

.PHONY : ComplexIntegral.s

# target to generate assembly for a file
ComplexIntegral.cpp.s:
	$(MAKE) -f CMakeFiles/T2.dir/build.make CMakeFiles/T2.dir/ComplexIntegral.cpp.s
	$(MAKE) -f CMakeFiles/T3.dir/build.make CMakeFiles/T3.dir/ComplexIntegral.cpp.s
	$(MAKE) -f CMakeFiles/fourierSeries.dir/build.make CMakeFiles/fourierSeries.dir/ComplexIntegral.cpp.s
.PHONY : ComplexIntegral.cpp.s

ComplexValue.o: ComplexValue.cpp.o

.PHONY : ComplexValue.o

# target to build an object file
ComplexValue.cpp.o:
	$(MAKE) -f CMakeFiles/T2.dir/build.make CMakeFiles/T2.dir/ComplexValue.cpp.o
	$(MAKE) -f CMakeFiles/T3.dir/build.make CMakeFiles/T3.dir/ComplexValue.cpp.o
	$(MAKE) -f CMakeFiles/fourierSeries.dir/build.make CMakeFiles/fourierSeries.dir/ComplexValue.cpp.o
.PHONY : ComplexValue.cpp.o

ComplexValue.i: ComplexValue.cpp.i

.PHONY : ComplexValue.i

# target to preprocess a source file
ComplexValue.cpp.i:
	$(MAKE) -f CMakeFiles/T2.dir/build.make CMakeFiles/T2.dir/ComplexValue.cpp.i
	$(MAKE) -f CMakeFiles/T3.dir/build.make CMakeFiles/T3.dir/ComplexValue.cpp.i
	$(MAKE) -f CMakeFiles/fourierSeries.dir/build.make CMakeFiles/fourierSeries.dir/ComplexValue.cpp.i
.PHONY : ComplexValue.cpp.i

ComplexValue.s: ComplexValue.cpp.s

.PHONY : ComplexValue.s

# target to generate assembly for a file
ComplexValue.cpp.s:
	$(MAKE) -f CMakeFiles/T2.dir/build.make CMakeFiles/T2.dir/ComplexValue.cpp.s
	$(MAKE) -f CMakeFiles/T3.dir/build.make CMakeFiles/T3.dir/ComplexValue.cpp.s
	$(MAKE) -f CMakeFiles/fourierSeries.dir/build.make CMakeFiles/fourierSeries.dir/ComplexValue.cpp.s
.PHONY : ComplexValue.cpp.s

CountCharacters.o: CountCharacters.cpp.o

.PHONY : CountCharacters.o

# target to build an object file
CountCharacters.cpp.o:
	$(MAKE) -f CMakeFiles/diaryCharacterStatistics.dir/build.make CMakeFiles/diaryCharacterStatistics.dir/CountCharacters.cpp.o
.PHONY : CountCharacters.cpp.o

CountCharacters.i: CountCharacters.cpp.i

.PHONY : CountCharacters.i

# target to preprocess a source file
CountCharacters.cpp.i:
	$(MAKE) -f CMakeFiles/diaryCharacterStatistics.dir/build.make CMakeFiles/diaryCharacterStatistics.dir/CountCharacters.cpp.i
.PHONY : CountCharacters.cpp.i

CountCharacters.s: CountCharacters.cpp.s

.PHONY : CountCharacters.s

# target to generate assembly for a file
CountCharacters.cpp.s:
	$(MAKE) -f CMakeFiles/diaryCharacterStatistics.dir/build.make CMakeFiles/diaryCharacterStatistics.dir/CountCharacters.cpp.s
.PHONY : CountCharacters.cpp.s

DiaryCharactersStatistics.o: DiaryCharactersStatistics.cpp.o

.PHONY : DiaryCharactersStatistics.o

# target to build an object file
DiaryCharactersStatistics.cpp.o:
	$(MAKE) -f CMakeFiles/diaryCharacterStatistics.dir/build.make CMakeFiles/diaryCharacterStatistics.dir/DiaryCharactersStatistics.cpp.o
.PHONY : DiaryCharactersStatistics.cpp.o

DiaryCharactersStatistics.i: DiaryCharactersStatistics.cpp.i

.PHONY : DiaryCharactersStatistics.i

# target to preprocess a source file
DiaryCharactersStatistics.cpp.i:
	$(MAKE) -f CMakeFiles/diaryCharacterStatistics.dir/build.make CMakeFiles/diaryCharacterStatistics.dir/DiaryCharactersStatistics.cpp.i
.PHONY : DiaryCharactersStatistics.cpp.i

DiaryCharactersStatistics.s: DiaryCharactersStatistics.cpp.s

.PHONY : DiaryCharactersStatistics.s

# target to generate assembly for a file
DiaryCharactersStatistics.cpp.s:
	$(MAKE) -f CMakeFiles/diaryCharacterStatistics.dir/build.make CMakeFiles/diaryCharacterStatistics.dir/DiaryCharactersStatistics.cpp.s
.PHONY : DiaryCharactersStatistics.cpp.s

Epicycle.o: Epicycle.cpp.o

.PHONY : Epicycle.o

# target to build an object file
Epicycle.cpp.o:
	$(MAKE) -f CMakeFiles/T2.dir/build.make CMakeFiles/T2.dir/Epicycle.cpp.o
	$(MAKE) -f CMakeFiles/T3.dir/build.make CMakeFiles/T3.dir/Epicycle.cpp.o
	$(MAKE) -f CMakeFiles/fourierSeries.dir/build.make CMakeFiles/fourierSeries.dir/Epicycle.cpp.o
.PHONY : Epicycle.cpp.o

Epicycle.i: Epicycle.cpp.i

.PHONY : Epicycle.i

# target to preprocess a source file
Epicycle.cpp.i:
	$(MAKE) -f CMakeFiles/T2.dir/build.make CMakeFiles/T2.dir/Epicycle.cpp.i
	$(MAKE) -f CMakeFiles/T3.dir/build.make CMakeFiles/T3.dir/Epicycle.cpp.i
	$(MAKE) -f CMakeFiles/fourierSeries.dir/build.make CMakeFiles/fourierSeries.dir/Epicycle.cpp.i
.PHONY : Epicycle.cpp.i

Epicycle.s: Epicycle.cpp.s

.PHONY : Epicycle.s

# target to generate assembly for a file
Epicycle.cpp.s:
	$(MAKE) -f CMakeFiles/T2.dir/build.make CMakeFiles/T2.dir/Epicycle.cpp.s
	$(MAKE) -f CMakeFiles/T3.dir/build.make CMakeFiles/T3.dir/Epicycle.cpp.s
	$(MAKE) -f CMakeFiles/fourierSeries.dir/build.make CMakeFiles/fourierSeries.dir/Epicycle.cpp.s
.PHONY : Epicycle.cpp.s

FourierSeries.o: FourierSeries.cpp.o

.PHONY : FourierSeries.o

# target to build an object file
FourierSeries.cpp.o:
	$(MAKE) -f CMakeFiles/T2.dir/build.make CMakeFiles/T2.dir/FourierSeries.cpp.o
	$(MAKE) -f CMakeFiles/T3.dir/build.make CMakeFiles/T3.dir/FourierSeries.cpp.o
	$(MAKE) -f CMakeFiles/fourierSeries.dir/build.make CMakeFiles/fourierSeries.dir/FourierSeries.cpp.o
.PHONY : FourierSeries.cpp.o

FourierSeries.i: FourierSeries.cpp.i

.PHONY : FourierSeries.i

# target to preprocess a source file
FourierSeries.cpp.i:
	$(MAKE) -f CMakeFiles/T2.dir/build.make CMakeFiles/T2.dir/FourierSeries.cpp.i
	$(MAKE) -f CMakeFiles/T3.dir/build.make CMakeFiles/T3.dir/FourierSeries.cpp.i
	$(MAKE) -f CMakeFiles/fourierSeries.dir/build.make CMakeFiles/fourierSeries.dir/FourierSeries.cpp.i
.PHONY : FourierSeries.cpp.i

FourierSeries.s: FourierSeries.cpp.s

.PHONY : FourierSeries.s

# target to generate assembly for a file
FourierSeries.cpp.s:
	$(MAKE) -f CMakeFiles/T2.dir/build.make CMakeFiles/T2.dir/FourierSeries.cpp.s
	$(MAKE) -f CMakeFiles/T3.dir/build.make CMakeFiles/T3.dir/FourierSeries.cpp.s
	$(MAKE) -f CMakeFiles/fourierSeries.dir/build.make CMakeFiles/fourierSeries.dir/FourierSeries.cpp.s
.PHONY : FourierSeries.cpp.s

a.o: a.cpp.o

.PHONY : a.o

# target to build an object file
a.cpp.o:
	$(MAKE) -f CMakeFiles/a.dir/build.make CMakeFiles/a.dir/a.cpp.o
.PHONY : a.cpp.o

a.i: a.cpp.i

.PHONY : a.i

# target to preprocess a source file
a.cpp.i:
	$(MAKE) -f CMakeFiles/a.dir/build.make CMakeFiles/a.dir/a.cpp.i
.PHONY : a.cpp.i

a.s: a.cpp.s

.PHONY : a.s

# target to generate assembly for a file
a.cpp.s:
	$(MAKE) -f CMakeFiles/a.dir/build.make CMakeFiles/a.dir/a.cpp.s
.PHONY : a.cpp.s

p/T1.o: p/T1.cpp.o

.PHONY : p/T1.o

# target to build an object file
p/T1.cpp.o:
	$(MAKE) -f CMakeFiles/T1.dir/build.make CMakeFiles/T1.dir/p/T1.cpp.o
.PHONY : p/T1.cpp.o

p/T1.i: p/T1.cpp.i

.PHONY : p/T1.i

# target to preprocess a source file
p/T1.cpp.i:
	$(MAKE) -f CMakeFiles/T1.dir/build.make CMakeFiles/T1.dir/p/T1.cpp.i
.PHONY : p/T1.cpp.i

p/T1.s: p/T1.cpp.s

.PHONY : p/T1.s

# target to generate assembly for a file
p/T1.cpp.s:
	$(MAKE) -f CMakeFiles/T1.dir/build.make CMakeFiles/T1.dir/p/T1.cpp.s
.PHONY : p/T1.cpp.s

p/T2.o: p/T2.cpp.o

.PHONY : p/T2.o

# target to build an object file
p/T2.cpp.o:
	$(MAKE) -f CMakeFiles/T2.dir/build.make CMakeFiles/T2.dir/p/T2.cpp.o
.PHONY : p/T2.cpp.o

p/T2.i: p/T2.cpp.i

.PHONY : p/T2.i

# target to preprocess a source file
p/T2.cpp.i:
	$(MAKE) -f CMakeFiles/T2.dir/build.make CMakeFiles/T2.dir/p/T2.cpp.i
.PHONY : p/T2.cpp.i

p/T2.s: p/T2.cpp.s

.PHONY : p/T2.s

# target to generate assembly for a file
p/T2.cpp.s:
	$(MAKE) -f CMakeFiles/T2.dir/build.make CMakeFiles/T2.dir/p/T2.cpp.s
.PHONY : p/T2.cpp.s

p/T3.o: p/T3.cpp.o

.PHONY : p/T3.o

# target to build an object file
p/T3.cpp.o:
	$(MAKE) -f CMakeFiles/T3.dir/build.make CMakeFiles/T3.dir/p/T3.cpp.o
.PHONY : p/T3.cpp.o

p/T3.i: p/T3.cpp.i

.PHONY : p/T3.i

# target to preprocess a source file
p/T3.cpp.i:
	$(MAKE) -f CMakeFiles/T3.dir/build.make CMakeFiles/T3.dir/p/T3.cpp.i
.PHONY : p/T3.cpp.i

p/T3.s: p/T3.cpp.s

.PHONY : p/T3.s

# target to generate assembly for a file
p/T3.cpp.s:
	$(MAKE) -f CMakeFiles/T3.dir/build.make CMakeFiles/T3.dir/p/T3.cpp.s
.PHONY : p/T3.cpp.s

p/T4.o: p/T4.cpp.o

.PHONY : p/T4.o

# target to build an object file
p/T4.cpp.o:
	$(MAKE) -f CMakeFiles/T4.dir/build.make CMakeFiles/T4.dir/p/T4.cpp.o
.PHONY : p/T4.cpp.o

p/T4.i: p/T4.cpp.i

.PHONY : p/T4.i

# target to preprocess a source file
p/T4.cpp.i:
	$(MAKE) -f CMakeFiles/T4.dir/build.make CMakeFiles/T4.dir/p/T4.cpp.i
.PHONY : p/T4.cpp.i

p/T4.s: p/T4.cpp.s

.PHONY : p/T4.s

# target to generate assembly for a file
p/T4.cpp.s:
	$(MAKE) -f CMakeFiles/T4.dir/build.make CMakeFiles/T4.dir/p/T4.cpp.s
.PHONY : p/T4.cpp.s

test.o: test.cpp.o

.PHONY : test.o

# target to build an object file
test.cpp.o:
	$(MAKE) -f CMakeFiles/test.dir/build.make CMakeFiles/test.dir/test.cpp.o
.PHONY : test.cpp.o

test.i: test.cpp.i

.PHONY : test.i

# target to preprocess a source file
test.cpp.i:
	$(MAKE) -f CMakeFiles/test.dir/build.make CMakeFiles/test.dir/test.cpp.i
.PHONY : test.cpp.i

test.s: test.cpp.s

.PHONY : test.s

# target to generate assembly for a file
test.cpp.s:
	$(MAKE) -f CMakeFiles/test.dir/build.make CMakeFiles/test.dir/test.cpp.s
.PHONY : test.cpp.s

utf8.o: utf8.cpp.o

.PHONY : utf8.o

# target to build an object file
utf8.cpp.o:
	$(MAKE) -f CMakeFiles/diaryCharacterStatistics.dir/build.make CMakeFiles/diaryCharacterStatistics.dir/utf8.cpp.o
.PHONY : utf8.cpp.o

utf8.i: utf8.cpp.i

.PHONY : utf8.i

# target to preprocess a source file
utf8.cpp.i:
	$(MAKE) -f CMakeFiles/diaryCharacterStatistics.dir/build.make CMakeFiles/diaryCharacterStatistics.dir/utf8.cpp.i
.PHONY : utf8.cpp.i

utf8.s: utf8.cpp.s

.PHONY : utf8.s

# target to generate assembly for a file
utf8.cpp.s:
	$(MAKE) -f CMakeFiles/diaryCharacterStatistics.dir/build.make CMakeFiles/diaryCharacterStatistics.dir/utf8.cpp.s
.PHONY : utf8.cpp.s

zhc.o: zhc.cpp.o

.PHONY : zhc.o

# target to build an object file
zhc.cpp.o:
	$(MAKE) -f CMakeFiles/diaryCharacterStatistics.dir/build.make CMakeFiles/diaryCharacterStatistics.dir/zhc.cpp.o
	$(MAKE) -f CMakeFiles/test.dir/build.make CMakeFiles/test.dir/zhc.cpp.o
	$(MAKE) -f CMakeFiles/T1.dir/build.make CMakeFiles/T1.dir/zhc.cpp.o
	$(MAKE) -f CMakeFiles/a.dir/build.make CMakeFiles/a.dir/zhc.cpp.o
	$(MAKE) -f CMakeFiles/T2.dir/build.make CMakeFiles/T2.dir/zhc.cpp.o
	$(MAKE) -f CMakeFiles/T3.dir/build.make CMakeFiles/T3.dir/zhc.cpp.o
	$(MAKE) -f CMakeFiles/T4.dir/build.make CMakeFiles/T4.dir/zhc.cpp.o
.PHONY : zhc.cpp.o

zhc.i: zhc.cpp.i

.PHONY : zhc.i

# target to preprocess a source file
zhc.cpp.i:
	$(MAKE) -f CMakeFiles/diaryCharacterStatistics.dir/build.make CMakeFiles/diaryCharacterStatistics.dir/zhc.cpp.i
	$(MAKE) -f CMakeFiles/test.dir/build.make CMakeFiles/test.dir/zhc.cpp.i
	$(MAKE) -f CMakeFiles/T1.dir/build.make CMakeFiles/T1.dir/zhc.cpp.i
	$(MAKE) -f CMakeFiles/a.dir/build.make CMakeFiles/a.dir/zhc.cpp.i
	$(MAKE) -f CMakeFiles/T2.dir/build.make CMakeFiles/T2.dir/zhc.cpp.i
	$(MAKE) -f CMakeFiles/T3.dir/build.make CMakeFiles/T3.dir/zhc.cpp.i
	$(MAKE) -f CMakeFiles/T4.dir/build.make CMakeFiles/T4.dir/zhc.cpp.i
.PHONY : zhc.cpp.i

zhc.s: zhc.cpp.s

.PHONY : zhc.s

# target to generate assembly for a file
zhc.cpp.s:
	$(MAKE) -f CMakeFiles/diaryCharacterStatistics.dir/build.make CMakeFiles/diaryCharacterStatistics.dir/zhc.cpp.s
	$(MAKE) -f CMakeFiles/test.dir/build.make CMakeFiles/test.dir/zhc.cpp.s
	$(MAKE) -f CMakeFiles/T1.dir/build.make CMakeFiles/T1.dir/zhc.cpp.s
	$(MAKE) -f CMakeFiles/a.dir/build.make CMakeFiles/a.dir/zhc.cpp.s
	$(MAKE) -f CMakeFiles/T2.dir/build.make CMakeFiles/T2.dir/zhc.cpp.s
	$(MAKE) -f CMakeFiles/T3.dir/build.make CMakeFiles/T3.dir/zhc.cpp.s
	$(MAKE) -f CMakeFiles/T4.dir/build.make CMakeFiles/T4.dir/zhc.cpp.s
.PHONY : zhc.cpp.s

# Help Target
help:
	@echo "The following are some of the valid targets for this Makefile:"
	@echo "... all (the default if no target is provided)"
	@echo "... clean"
	@echo "... depend"
	@echo "... rebuild_cache"
	@echo "... edit_cache"
	@echo "... diaryCharacterStatistics"
	@echo "... test"
	@echo "... T1"
	@echo "... a"
	@echo "... T2"
	@echo "... T3"
	@echo "... fourierSeries"
	@echo "... T4"
	@echo "... ComplexIntegral.o"
	@echo "... ComplexIntegral.i"
	@echo "... ComplexIntegral.s"
	@echo "... ComplexValue.o"
	@echo "... ComplexValue.i"
	@echo "... ComplexValue.s"
	@echo "... CountCharacters.o"
	@echo "... CountCharacters.i"
	@echo "... CountCharacters.s"
	@echo "... DiaryCharactersStatistics.o"
	@echo "... DiaryCharactersStatistics.i"
	@echo "... DiaryCharactersStatistics.s"
	@echo "... Epicycle.o"
	@echo "... Epicycle.i"
	@echo "... Epicycle.s"
	@echo "... FourierSeries.o"
	@echo "... FourierSeries.i"
	@echo "... FourierSeries.s"
	@echo "... a.o"
	@echo "... a.i"
	@echo "... a.s"
	@echo "... p/T1.o"
	@echo "... p/T1.i"
	@echo "... p/T1.s"
	@echo "... p/T2.o"
	@echo "... p/T2.i"
	@echo "... p/T2.s"
	@echo "... p/T3.o"
	@echo "... p/T3.i"
	@echo "... p/T3.s"
	@echo "... p/T4.o"
	@echo "... p/T4.i"
	@echo "... p/T4.s"
	@echo "... test.o"
	@echo "... test.i"
	@echo "... test.s"
	@echo "... utf8.o"
	@echo "... utf8.i"
	@echo "... utf8.s"
	@echo "... zhc.o"
	@echo "... zhc.i"
	@echo "... zhc.s"
.PHONY : help



#=============================================================================
# Special targets to cleanup operation of make.

# Special rule to run CMake to check the build system integrity.
# No rule that depends on this can have commands that come from listfiles
# because they might be regenerated.
cmake_check_build_system:
	$(CMAKE_COMMAND) -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 0
.PHONY : cmake_check_build_system

